[package]
name = "template-rust"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "^4.4", features = ["derive"] }
rand = "^0.8"
tracing = "^0.1"
tracing-subscriber = "^0.3"
